export const products = [
  {
    id: Math.round(Math.random() * 21),
    name: "Watch",
    description:
      "OLEVS Mens Chronograph Watch Gold Silver Stainless Steel Chain Quartz Wrist Watches Business Dress Waterproof Luminous Date Watch.",
    category: "General",
    MRP: 3900.0,
    discount: Math.round(Math.random() * 77),
    stock: Math.round(Math.random() * 14),
    quantity: 1,
    img: "https://rukminim2.flixcart.com/image/480/640/xif0q/watch/g/w/j/analog-stainless-steel-chain-wrist-watches-for-boy-and-men-watch-original-imagvhn9zwwfzzgn.jpeg?q=90",
  },
  {
    id: Math.round(Math.random() * 21),
    name: "Desk Lamp",
    description:
      "WEIRD WOLF 3 Colour Mode LED Study/Table/Desk Lamp with Pen Holder, 6 Month Warranty(Plastic, White, Pack of 1)",
    category: "General",
    MRP: 22.0,
    discount: Math.round(Math.random() * 77),
    stock: Math.round(Math.random() * 14),
    quantity: 1,
    img: "https://www.ikea.com/in/en/images/products/roedflik-desk-lamp-light-beige__1327054_pe944348_s5.jpg",
  },
  {
    id: Math.round(Math.random() * 21),
    name: "Sunglasses",
    description:
      "ELEGANTE Sunglasses for Women Fashion Ladies Shades Wrap Frame Trendy Stylish Sun Glasses UV Protection.",
    category: "General",
    MRP: 1299.0,
    discount: Math.round(Math.random() * 77),
    stock: Math.round(Math.random() * 14),
    quantity: 1,
    img: "https://adn-static1.nykaa.com/nykdesignstudio-images/pub/media/catalog/product/b/3/b3a68c5NHY_TEDSM00001019_1.jpg?rnd=20200526195200&tr=w-512",
  },
  {
    id: Math.round(Math.random() * 21),
    name: "Water Bottle",
    description:
      "CELLO H2O Glass Fridge Water Bottle with Plastic Cap Set of 3, 920ml, Blue | Leakproof & Durable | Wide Mouth, Easy To Clean | Multi Set Glass for Kitchen, Home, Office, Gym, Travel",
    category: "General",
    MRP: 12.0,
    discount: Math.round(Math.random() * 77),
    stock: Math.round(Math.random() * 14),
    quantity: 1,
    img: "https://sc04.alicdn.com/kf/H6a6a2ef146a24a7aaa34e2c698a7ed23m.jpg",
  },
  {
    id: Math.round(Math.random() * 21),
    name: "Hiking Bag",
    description:
      "Impulse 5 Compartment Rucksack Bag 60 Litres Travel Bag For Travel Backpack For Hiking Trekking Tourist Bag For Men Camping Keep Discovering Light Blue With 1 Year Warranty",
    category: "General",
    MRP: 1300.0,
    discount: Math.round(Math.random() * 77),
    stock: Math.round(Math.random() * 14),
    quantity: 1,
    img: "https://images.jdmagicbox.com/quickquotes/images_main/hiker-s-way-80-ltrs-farpoint-red-black-internal-frame-rucksack-bags-backpacks-travel-bag-hiking-bag-camping-bag-trekking-bags-for-men-and-women-with-waterproof-compartment-and-rain-cover-hw-8001-red-179318202-qo0ax.jpg",
  },
  {
    id: Math.round(Math.random() * 21),
    name: "Audi r8",
    description:
      "Audi R8 is a 2 seater Coupe with the last recorded MRP of Rs. 2.30 - 2.72 Crore. It is available in 2 variants, 5204 cc engine option and 2 transmission options : Manual and Automatic. The R8 is available in 10 colours. Audi R8 mileage is 6.71 kmpl.",
    category: "General",
    MRP: 79245.0,
    discount: Math.round(Math.random() * 77),
    stock: Math.round(Math.random() * 14),
    quantity: 1,
    img: "https://cdn.motor1.com/images/mgl/vxoJ0Y/s3/2023-audi-r8-v10-gt-rwd.jpg",
  },
  {
    id: Math.round(Math.random() * 21),
    name: "Plant stand",
    description:
      "ORILEY 4 Pcs Round Plant Stand Galvanised Metal Flower Pot Holder Rust Resistant Gamla Support Corner Rack Outdoor Display Shelf for Home Garden Balcony Decoration (Black)",
    category: "General",
    MRP: 399.0,
    discount: Math.round(Math.random() * 77),
    stock: Math.round(Math.random() * 14),
    quantity: 1,
    img: "https://m.media-amazon.com/images/I/61t9NUZRGRL._SX679_.jpg",
  },
  {
    id: Math.round(Math.random() * 21),
    name: "Football",
    description:
      "Nivia Storm Football, Size 5, Rubberized with perfect grip and durability, ideal for training and match.",
    category: "Sports",
    MRP: 18.0,
    discount: Math.round(Math.random() * 77),
    stock: Math.round(Math.random() * 14),
    quantity: 1,
    img: "https://www.englishclub.com/images/vocabulary/sports/fifa-brazil-2014-ball.jpg",
  },
  {
    id: Math.round(Math.random() * 21),
    name: "Badminton Racket",
    description:
      "Yonex Nanoray Light 18i Graphite Badminton Racquet, lightweight, high-tension, suited for advanced players.",
    category: "Sports",
    MRP: 29.0,
    discount: Math.round(Math.random() * 77),
    stock: Math.round(Math.random() * 14),
    quantity: 1,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSG7f80umB2vgtlHUk-EVRdBHIMheNnkiRcLQ&s",
  },
  {
    id: Math.round(Math.random() * 21),
    name: "Cricket Bat",
    description:
      "SG RSD Spark English Willow Cricket Bat, full size for adults, high-quality wood for powerful shots.",
    category: "Sports",
    MRP: 65.0,
    discount: Math.round(Math.random() * 77),
    stock: Math.round(Math.random() * 14),
    quantity: 1,
    img: "https://www.prodirectsport.com/-/media/article-content/cricket/buying-advice/cricket-bat-size-guide/article-bb-cricket-product-advice-articles-1.jpg",
  },
  {
    id: Math.round(Math.random() * 21),
    name: "Table Tennis Set",
    description:
      "GKI Fasto Table Tennis Bat Set with two bats, three balls, convenient carrying cover.",
    category: "Sports",
    MRP: 15.0,
    discount: Math.round(Math.random() * 77),
    stock: Math.round(Math.random() * 14),
    quantity: 1,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmFJ9WZJQS2IPT7IEW6lNrle1p1UQaTwfOdw&s",
  },
  {
    id: Math.round(Math.random() * 21),
    name: "Skipping Rope",
    description:
      "Vector X Skipping Rope for Men and Women, adjustable length, foam handles for better grip.",
    category: "Sports",
    MRP: 6.0,
    discount: Math.round(Math.random() * 77),
    stock: Math.round(Math.random() * 14),
    quantity: 1,
    img: "https://contents.mediadecathlon.com/p1899141/682c88daaeb6785c264ccc027406ea84/p1899141.jpg",
  },
  {
    id: Math.round(Math.random() * 21),
    name: "Basketball",
    description:
      "Cosco Dribble Basketball Size 6, Synthetic rubber, strong grip, suitable for indoor and outdoor play.",
    category: "Sports",
    MRP: 22.0,
    discount: Math.round(Math.random() * 77),
    stock: Math.round(Math.random() * 14),
    quantity: 1,
    img: "https://media.istockphoto.com/id/165960691/vector/basketball-arts.jpg?s=612x612&w=0&k=20&c=iTpussHsVcCBTYBNVUkHq6KgUOczhZhgKPdOy1cr3wA=",
  },
  {
    id: Math.round(Math.random() * 21),
    name: "Gaming Laptop",
    description:
      "ASUS ROG Zephyrus G14 Gaming Laptop with AMD Ryzen 9, 16GB RAM, 1TB SSD, 14-inch FHD Display.",
    category: "Electronics",
    MRP: 1500.0,
    discount: Math.round(Math.random() * 77),
    stock: Math.round(Math.random() * 14),
    quantity: 1,
    img: "https://cdn.mos.cms.futurecdn.net/3VpzFCHbyJ7i4JdA3ZdD6V.jpg",
  },
  {
    id: Math.round(Math.random() * 21),
    name: "Mechanical Keyboard",
    description:
      "Corsair K95 RGB Platinum Mechanical Gaming Keyboard with Cherry MX Speed switches, customizable RGB lighting.",
    category: "Electronics",
    MRP: 200.0,
    discount: Math.round(Math.random() * 77),
    stock: Math.round(Math.random() * 14),
    quantity: 1,
    img: "https://images.indianexpress.com/2021/06/Corsair-Mechanical-Keyboard.jpg",
  },
  {
    id: Math.round(Math.random() * 21),
    name: "Wireless Mouse",
    description:
      "Lenovo 150 Wireless Compact Mouse, 1K DPI Optical sensor, 2.4GHz Wireless NanoUSB, 10m range, 3button(left,right,scroll) upto 3M left/right clicks, 10month battery, Ambidextrous, Ergonomic, GY77L52638",
    category: "Electronics",
    MRP: 47.0,
    discount: Math.round(Math.random() * 77),
    stock: Math.round(Math.random() * 14),
    quantity: 1,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAMbCOcASgoyO_A48_azDuXxJlwEWq8vLFNA&s",
  },
  {
    id: Math.round(Math.random() * 21),
    name: "Gaming Joystick",
    description:
      "Thrustmaster T.16000M FCS HOTAS Flight Control System, precise and ergonomic joystick for flight simulators.",
    category: "Electronics",
    MRP: 180.0,
    discount: Math.round(Math.random() * 77),
    stock: Math.round(Math.random() * 14),
    quantity: 1,
    img: "https://m.media-amazon.com/images/I/71kVWZfiVxL.jpg",
  },
  {
    id: Math.round(Math.random() * 21),
    name: "Desktop CPU",
    description:
      "Intel Core i7-13700K Processor, 16 cores, unlocked for high performance desktop computing.",
    category: "Electronics",
    MRP: 420.0,
    discount: Math.round(Math.random() * 77),
    stock: Math.round(Math.random() * 14),
    quantity: 1,
    img: "https://vrlatech.com/wp-content/uploads/2025/02/Phoenix-Teal-RTX-5090-1-scaled.jpg",
  },
  {
    id: Math.round(Math.random() * 21),
    name: "Laptop",
    description:
      "Lenovo Yoga Slim 7 (Smartchoice) Aura Edition Intel Core Ultra 5 226V,Copilot+ AI PC(16GB RAM/1TB SSD/14(35.5cm)/WUXGA OLED/40 Tops/Windows 11/Office Home 2024/Grey/1.19Kg), 83JX005FIN AI Laptop",
    category: "Electronics",
    MRP: 1200.0,
    discount: Math.round(Math.random() * 77),
    stock: Math.round(Math.random() * 14),
    quantity: 1,
    img: "https://static0.makeuseofimages.com/wordpress/wp-content/uploads/2017/08/revive-windows-xp-windows10.jpg",
  },
  {
    id: Math.round(Math.random() * 21),
    name: "Noise Cancelling Headphones",
    description:
      "Sony WH-1000XM4 Wireless Noise-Cancelling Headphones with up to 30 hours battery life.",
    category: "Electronics",
    MRP: 350.0,
    discount: Math.round(Math.random() * 77),
    stock: Math.round(Math.random() * 14),
    quantity: 1,
    img: "https://kreo-tech.com/cdn/shop/files/Artboard_1_9.png?v=1753673089",
  },
  {
    id: Math.round(Math.random() * 21),
    name: "Samsung S24",
    description:
      "Samsung Galaxy S24 FE 5G AI Smartphone (Blue, 8GB RAM, 128GB Storage)",
    category: "Electronics",
    MRP: 899.0,
    discount: Math.round(Math.random() * 77),
    stock: Math.round(Math.random() * 14),
    quantity: 1,
    img: "https://www.busiboutique.com/medias/boutique/425969/61cfcf77-fee2-4bf6-9663-c9337e1d9d66.jpg",
  },
];
